import { useEffect, useState } from "react";
import { Alert, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { Stack, useLocalSearchParams, useRouter } from "expo-router";
import { Controller, useForm } from "react-hook-form";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { mobileApi } from "@/lib/api";
import { clearDraft, loadDraft, saveDraft } from "@/lib/query";

type Values = { fullName: string; phone: string; email: string; city: string; address: string; leadSource: string; notes: string };
const defaults: Values = { fullName: "", phone: "", email: "", city: "", address: "", leadSource: "", notes: "" };
export default function NewRecordScreen() {
  const params = useLocalSearchParams<{ resource?: string }>(); const resource = params.resource === "customers" ? "customers" : "enquiries"; const label = resource === "customers" ? "customer" : "enquiry";
  const router = useRouter(); const queryClient = useQueryClient(); const form = useForm<Values>({ defaultValues: defaults }); const [scope, setScope] = useState<{ userId: string; companyId: string } | null>(null);
  useEffect(() => { void mobileApi.session().then(async (context) => { const next = { userId: context.user.id, companyId: context.tenant.companyId }; setScope(next); const draft = await loadDraft<Values>(next.userId, next.companyId, resource); if (draft) form.reset(draft); }); }, [form, resource]);
  useEffect(() => { if (!scope) return; const subscription = form.watch((value) => { void saveDraft(scope.userId, scope.companyId, resource, value); }); return () => subscription.unsubscribe(); }, [form, resource, scope]);
  const create = useMutation({ mutationFn: (values: Values) => mobileApi.createRecord(resource, values), onSuccess: async () => { if (scope) await clearDraft(scope.userId, scope.companyId, resource); await queryClient.invalidateQueries({ queryKey: [resource] }); router.back(); }, onError: (error) => Alert.alert(`Could not create ${label}`, error instanceof Error ? error.message : "Try again") });
  return <KeyboardAvoidingView behavior={Platform.OS === "ios" ? "padding" : undefined} style={styles.page}><Stack.Screen options={{ headerShown: true, title: `New ${label}` }} /><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><Text style={styles.title}>New {label}</Text><Text style={styles.copy}>Required details are kept intentionally short for field entry. Your draft stays on this device until submitted.</Text><Field control={form.control} name="fullName" label="Full name" required /><Field control={form.control} name="phone" label="Phone" keyboardType="phone-pad" required /><Field control={form.control} name="email" label="Email" keyboardType="email-address" /><Field control={form.control} name="city" label="City" /><Field control={form.control} name="address" label="Address" multiline /><Field control={form.control} name="leadSource" label="Lead source" /><Field control={form.control} name="notes" label="Notes" multiline /><Pressable disabled={create.isPending} onPress={form.handleSubmit((values) => create.mutate(values))} style={styles.submit}><Text style={styles.submitText}>{create.isPending ? "Saving..." : `Create ${label}`}</Text></Pressable></ScrollView></KeyboardAvoidingView>;
}
function Field({ control, name, label, required = false, keyboardType = "default", multiline = false }: { control: ReturnType<typeof useForm<Values>>["control"]; name: keyof Values; label: string; required?: boolean; keyboardType?: "default" | "phone-pad" | "email-address"; multiline?: boolean }) { return <Controller control={control} name={name} rules={required ? { required: `${label} is required` } : undefined} render={({ field: { onChange, onBlur, value }, fieldState }) => <View><Text style={styles.label}>{label}{required ? " *" : ""}</Text><TextInput accessibilityLabel={label} autoCapitalize={keyboardType === "email-address" ? "none" : "sentences"} keyboardType={keyboardType} multiline={multiline} onBlur={onBlur} onChangeText={onChange} style={[styles.input, multiline && styles.multiline, fieldState.error && styles.inputError]} value={value} />{fieldState.error && <Text style={styles.error}>{fieldState.error.message}</Text>}</View>} />; }
const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: "#f8fafc" }, content: { padding: 18, paddingBottom: 50, gap: 14 }, title: { fontSize: 28, fontWeight: "800", color: "#06173f" }, copy: { color: "#64748b", lineHeight: 21, marginBottom: 4 }, label: { color: "#334155", fontWeight: "700", marginBottom: 6 }, input: { backgroundColor: "white", borderWidth: 1, borderColor: "#cbd5e1", borderRadius: 12, minHeight: 48, paddingHorizontal: 14, fontSize: 16 }, multiline: { minHeight: 96, paddingTop: 12, textAlignVertical: "top" }, inputError: { borderColor: "#ef4444" }, error: { color: "#b91c1c", fontSize: 12, marginTop: 4 }, submit: { backgroundColor: "#0f766e", padding: 16, alignItems: "center", borderRadius: 12, marginTop: 8 }, submitText: { color: "white", fontWeight: "800", fontSize: 16 } });
