import { useEffect, useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { Stack, useLocalSearchParams } from "expo-router";
import { mobileApi } from "@/lib/api";
import { colors } from "@/theme";

export default function FieldWorkDetail() {
  const { resource, id } = useLocalSearchParams<{ resource: "projects" | "site-surveys"; id: string }>();
  const [record, setRecord] = useState<Record<string, unknown> | null>(null); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  async function load() { if (!id) return; try { const result = resource === "projects" ? await mobileApi.fieldProject(id) : await mobileApi.fieldSurvey(id); setRecord(result.data); } catch (value) { setError(value instanceof Error ? value.message : "Unable to load assigned work."); } }
  // load intentionally follows the active route identity.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { void load(); }, [id, resource]);
  const status = String(record?.project_status ?? record?.survey_status ?? "");
  const next = resource === "projects" ? status === "installation_scheduled" ? "installation_in_progress" : status === "installation_in_progress" ? "installation_completed" : null : status === "scheduled" || status === "rescheduled" ? "in_progress" : status === "in_progress" ? "completed" : null;
  async function update() { if (!id || !next) return; try { setSaving(true); if (resource === "projects") await mobileApi.updateFieldProjectStatus(id, next as "installation_in_progress" | "installation_completed"); else await mobileApi.updateFieldSurveyStatus(id, next as "in_progress" | "completed"); await load(); } catch (value) { setError(value instanceof Error ? value.message : "Status update failed."); } finally { setSaving(false); } }
  return <><Stack.Screen options={{ title: resource === "projects" ? "Project" : "Site survey" }} /><ScrollView contentContainerStyle={styles.content}>{error ? <Text style={styles.error}>{error}</Text> : null}{record ? <><Text style={styles.code}>{String(record.project_code ?? record.survey_code ?? "Assigned work")}</Text><Text style={styles.title}>{String(record.project_name ?? record.customer_name ?? record.contact_name ?? "Field work")}</Text><Text style={styles.status}>{status.replaceAll("_", " ")}</Text><View style={styles.card}>{Object.entries(record).filter(([key]) => ["customer_phone","contact_phone","installation_address","site_address","system_capacity_kw","start_date","expected_completion_date","scheduled_date","scheduled_time","field_notes","address_notes","remarks"].includes(key)).map(([key, value]) => <View key={key} style={styles.item}><Text style={styles.label}>{key.replaceAll("_", " ")}</Text><Text style={styles.value}>{value == null ? "-" : String(value)}</Text></View>)}</View><View style={styles.card}><Text style={styles.next}>Next Step</Text>{next ? <Pressable disabled={saving} onPress={update} style={styles.button}><Text style={styles.buttonText}>{saving ? "Updating..." : "Update Status"}</Text></Pressable> : <Text style={styles.value}>No status update is available. Completed work is read-only.</Text>}</View></> : null}</ScrollView></>;
}
const styles = StyleSheet.create({ content: { padding: 18, paddingBottom: 40, backgroundColor: colors.background, flexGrow: 1 }, code: { color: colors.muted, fontSize: 12, fontWeight: "800" }, title: { color: colors.navy, fontSize: 25, fontWeight: "900", marginTop: 5 }, status: { color: colors.orange, fontWeight: "900", textTransform: "capitalize", marginTop: 10 }, card: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: 16, padding: 16, marginTop: 18 }, item: { marginBottom: 14 }, label: { color: colors.muted, textTransform: "capitalize", fontSize: 11, fontWeight: "800" }, value: { color: colors.ink, fontSize: 14, marginTop: 4 }, next: { color: colors.navy, fontSize: 17, fontWeight: "900", marginBottom: 14 }, button: { backgroundColor: colors.orange, minHeight: 48, borderRadius: 12, alignItems: "center", justifyContent: "center" }, buttonText: { color: "white", fontWeight: "900" }, error: { color: colors.danger } });
