import { useCallback, useEffect, useMemo, useState, type FormEvent, type ReactNode } from "react";
import { useAuth } from "../../app/AuthProvider";
import { PageHeader } from "../../components/PageHeader";
import { TablePagination, useTablePagination } from "../../components/TablePagination";
import { useToast } from "../../components/ui/ToastProvider";
import { env } from "../../config/env";
import {
  AccessDenied,
  Badge,
  Button,
  ConfirmDialog,
  EmptyState,
  LoadingSkeleton,
  Modal,
  SearchInput,
  SelectInput,
  TextArea,
  TextInput,
  Toolbar,
} from "../crm/CrmComponents";
import { formatDateTime, hasPermission, labelize } from "../crm/crmUtils";
import {
  createStaff,
  deactivateStaffForSeatLimit,
  deleteInvitedStaff,
  fetchOrganizationSettings,
  fetchSettingsRoles,
  fetchSettingsStaff,
  resendStaffInvite,
  uploadCompanyLogo,
  updateOrganizationSettings,
  updateStaff,
} from "./settingsApi";
import type {
  OrganizationSettingsFormValues,
  SettingsRole,
  SettingsStaff,
  StaffFormValues,
  StaffStatus,
} from "./types";
import {
  emptyOrganizationSettingsForm,
  emptyStaffForm,
  organizationSettingsToForm,
  staffStatusOptions,
  staffToForm,
  validateStaffForm,
} from "./settingsUtils";
import { CompanyLogoUploader } from "./CompanyLogoUploader";
import { NotificationPreferencesSection } from "./NotificationPreferencesSection";
import { BillingInvoicesSection } from "./BillingInvoicesSection";

type StaffFormState = {
  mode: "create" | "edit";
  staff: SettingsStaff | null;
  values: StaffFormValues;
};

export function SettingsPage() {
  const { profile, permissions, subscription } = useAuth();

  if (profile?.is_super_admin) {
    return <PlatformSettingsPage />;
  }

  const canManageSettings = hasPermission(profile, permissions, "settings", "update");
  const canReduceSeats = Boolean(
    subscription?.is_admin && !subscription.write_allowed,
  );

  if (!canManageSettings && !canReduceSeats) {
    return (
      <AccessDenied
        title="Settings are not available"
        description="Your role needs settings:update access to manage organization and staff."
      />
    );
  }

  if (!canManageSettings && canReduceSeats) {
    return (
      <div className="space-y-4">
        <PageHeader
          title="Prepare for Bizlee Core"
          description="Deactivate active or invited staff until only three total users remain, then return to Billing & Plans."
        />
        <StaffManagementPage reductionOnly />
      </div>
    );
  }

  return (
    <div className="space-y-4">
      <PageHeader
        title="Settings"
        description="Manage organization branding and staff access."
      />

      <OrganizationSettingsPage />
      <BillingInvoicesSection />
      <NotificationPreferencesSection />
      <StaffManagementPage />
    </div>
  );
}

function PlatformSettingsPage() {
  return (
    <div className="space-y-6">
      <PageHeader
        title="Platform Settings"
        description="Super Admin defaults and platform metadata for EPC workspace onboarding."
      />

      <section className="grid gap-4 lg:grid-cols-3">
        <SettingsCard
          title="Application"
          description="SolarOS platform workspace for EPC company onboarding."
        />
        <SettingsCard
          title="Supabase"
          description={
            env.supabaseUrl
              ? "Supabase project URL is configured for the frontend."
              : "Supabase project URL is not configured in the frontend environment."
          }
        />
        <SettingsCard
          title="Invite Redirect"
          description="EPC admin invite links are generated by the Supabase Edge Function from APP_BASE_URL or request origin."
        />
      </section>

      <section className="rounded-xl border border-stone-200 bg-white p-5 shadow-sm">
        <SectionTitle
          title="Phase 2 Subscription Defaults"
          description="Subscription and financial controls are intentionally read-only placeholders in Phase 1."
        />
        <div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">
          <Detail label="Default Plan" value="Coming in Phase 2" />
          <Detail label="Billing Cycle" value="Coming in Phase 2" />
          <Detail label="Trial Policy" value="Coming in Phase 2" />
          <Detail label="Outstanding Amount" value="Coming in Phase 2" />
          <Detail label="Last Invoice" value="Coming in Phase 2" />
          <Detail label="Last Payment" value="Coming in Phase 2" />
        </div>
      </section>
    </div>
  );
}

export function SettingsOverviewPage() {
  return (
    <div className="grid gap-4 md:grid-cols-3">
      <SettingsCard
        title="Organization"
        description="Company logo, tax details, banking, and regional defaults."
      />
      <SettingsCard
        title="Staff"
        description="Pre-created profiles, status changes, and role assignment."
      />
      <SettingsCard
        title="Roles"
        description="Role records and CRUD permission matrix by module."
      />
    </div>
  );
}

export function OrganizationSettingsPage() {
  const { organization, profile, refresh, session } = useAuth();
  const { showToast } = useToast();
  const [values, setValues] = useState<OrganizationSettingsFormValues>(
    emptyOrganizationSettingsForm(),
  );
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    async function loadSettings() {
      try {
        setLoading(true);
        setError(null);
        const settings = await fetchOrganizationSettings();
        setValues(
          withEnrollmentDefaults(
            organizationSettingsToForm(settings),
            {
              companyName: organization.id ? organization.name : null,
              contactPerson: profile?.full_name,
              contactEmail: session?.user.email,
              contactPhone: profile?.phone,
            },
          ),
        );
      } catch (nextError) {
        setError(
          nextError instanceof Error
            ? nextError.message
            : "Unable to load organization settings.",
        );
      } finally {
        setLoading(false);
      }
    }

    void loadSettings();
  }, [
    organization.id,
    organization.name,
    profile?.full_name,
    profile?.phone,
    session?.user.email,
  ]);

  async function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();

    try {
      setSaving(true);
      const updatedSettings = await updateOrganizationSettings({
        ...values,
        timezone: values.timezone || "Asia/Kolkata",
        currency: values.currency || "INR",
        date_format: values.date_format || "DD/MM/YYYY",
      });
      setValues(organizationSettingsToForm(updatedSettings));
      await refresh();
      showToast("Organization settings updated.", "success");
    } catch (nextError) {
      showToast(
        nextError instanceof Error
          ? nextError.message
          : "Organization settings update failed.",
        "error",
      );
    } finally {
      setSaving(false);
    }
  }

  const update = (key: keyof OrganizationSettingsFormValues, value: string) =>
    setValues((current) => ({ ...current, [key]: value }));

  async function handleLogoUpload(logo: Blob) {
    const publicUrl = await uploadCompanyLogo(profile, logo);
    const updatedSettings = await updateOrganizationSettings({
      company_logo_url: publicUrl,
    });
    setValues(organizationSettingsToForm(updatedSettings));
    await refresh();
    showToast("Company logo updated.", "success");
  }

  if (loading) {
    return <LoadingSkeleton />;
  }

  if (error) {
    return <EmptyState title="Could not load settings" description={error} />;
  }

  return (
    <form
      className="overflow-hidden rounded-2xl border border-stone-200 bg-white shadow-sm"
      onSubmit={handleSubmit}
    >
      <div className="border-b border-stone-200 px-4 py-4 sm:px-6">
        <SectionTitle
          title="Company Profile"
          description="Keep your business identity, contact information, and banking details up to date."
        />
      </div>

      <div className="space-y-4 bg-stone-50/70 p-3 sm:p-5">
        <section aria-labelledby="brand-identity-heading">
          <div className="mb-3 flex items-center justify-between gap-3">
            <div>
              <h3
                id="brand-identity-heading"
                className="text-sm font-semibold text-slate-950"
              >
                Brand identity
              </h3>
              <p className="mt-0.5 text-xs leading-5 text-slate-500">
                This logo appears across your workspace and customer documents.
              </p>
            </div>
            <span className="hidden rounded-full bg-orange-100 px-2.5 py-1 text-xs font-semibold text-orange-700 sm:inline-flex">
              Company logo
            </span>
          </div>
          <CompanyLogoUploader
            currentUrl={values.company_logo_url}
            disabled={saving}
            onUpload={handleLogoUpload}
          />
        </section>

        <div className="grid items-start gap-4 xl:grid-cols-2">
          <ProfileSettingsCard
            title="Company information"
            description="Business and primary contact details"
          >
            <TextInput
              label="Company Name"
              value={values.company_name}
              onChange={(value) => update("company_name", value)}
            />
            <TextArea
              className="block"
              label="Address"
              value={values.address}
              onChange={(value) => update("address", value)}
            />
            <div className="grid gap-3 sm:grid-cols-2">
              <TextInput
                label="Contact Person"
                value={values.contact_person}
                onChange={(value) => update("contact_person", value)}
              />
              <TextInput
                label="Contact Email"
                type="email"
                value={values.contact_email}
                onChange={(value) => update("contact_email", value)}
              />
            </div>
            <div className="grid gap-3 sm:grid-cols-2">
              <TextInput
                label="Contact Phone"
                value={values.contact_phone}
                onChange={(value) => update("contact_phone", value)}
              />
              <TextInput
                label="GST Number"
                value={values.gst_number}
                onChange={(value) => update("gst_number", value)}
              />
            </div>
          </ProfileSettingsCard>

          <ProfileSettingsCard
            title="Bank details"
            description="Account information used on financial documents"
          >
            <TextInput
              label="Account Holder Name"
              value={values.bank_account_holder_name}
              onChange={(value) => update("bank_account_holder_name", value)}
            />
            <TextInput
              label="Account Number"
              value={values.bank_account_number}
              onChange={(value) => update("bank_account_number", value)}
            />
            <div className="grid gap-3 sm:grid-cols-2">
              <TextInput
                label="Bank Name"
                value={values.bank_name}
                onChange={(value) => update("bank_name", value)}
              />
              <TextInput
                label="Account Type"
                value={values.bank_account_type}
                onChange={(value) => update("bank_account_type", value)}
              />
            </div>
            <TextInput
              label="IFSC Code"
              value={values.bank_ifsc_code}
              onChange={(value) => update("bank_ifsc_code", value)}
            />
            <div className="-mx-4 -mb-4 mt-1 flex justify-end border-t border-stone-100 bg-stone-50/70 p-4 [&>button]:w-full sm:[&>button]:w-auto">
              <Button type="submit" disabled={saving}>
                {saving ? "Saving..." : "Save Settings"}
              </Button>
            </div>
          </ProfileSettingsCard>
        </div>
      </div>
    </form>
  );
}

function withEnrollmentDefaults(
  values: OrganizationSettingsFormValues,
  defaults: {
    companyName?: string | null;
    contactPerson?: string | null;
    contactEmail?: string | null;
    contactPhone?: string | null;
  },
): OrganizationSettingsFormValues {
  return {
    ...values,
    company_name: values.company_name || defaults.companyName || "",
    contact_person: values.contact_person || defaults.contactPerson || "",
    contact_email: values.contact_email || defaults.contactEmail || "",
    contact_phone: values.contact_phone || defaults.contactPhone || "",
  };
}

export function StaffManagementPage({ reductionOnly = false }: { reductionOnly?: boolean }) {
  const { showToast } = useToast();
  const [staff, setStaff] = useState<SettingsStaff[]>([]);
  const [roles, setRoles] = useState<SettingsRole[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [search, setSearch] = useState("");
  const [formState, setFormState] = useState<StaffFormState | null>(null);
  const [formErrors, setFormErrors] = useState<Record<string, string>>({});
  const [saving, setSaving] = useState(false);
  const [statusTarget, setStatusTarget] = useState<SettingsStaff | null>(null);
  const [statusSaving, setStatusSaving] = useState(false);
  const [resendingStaffId, setResendingStaffId] = useState<string | null>(null);
  const [deleteTarget, setDeleteTarget] = useState<SettingsStaff | null>(null);
  const [deleting, setDeleting] = useState(false);
  const [openStaffMenuId, setOpenStaffMenuId] = useState<string | null>(null);

  const loadData = useCallback(async () => {
    try {
      setLoading(true);
      setError(null);
      const [nextStaff, nextRoles] = await Promise.all([
        fetchSettingsStaff(),
        reductionOnly ? Promise.resolve([]) : fetchSettingsRoles(),
      ]);
      setStaff(nextStaff);
      setRoles(nextRoles);
    } catch (nextError) {
      setError(
        nextError instanceof Error ? nextError.message : "Unable to load staff.",
      );
    } finally {
      setLoading(false);
    }
  }, [reductionOnly]);

  useEffect(() => {
    void loadData();
  }, [loadData]);

  const filteredStaff = useMemo(() => {
    const normalizedSearch = search.trim().toLowerCase();

    if (!normalizedSearch) {
      return staff;
    }

    return staff.filter((member) =>
      [member.full_name, member.phone, member.email, member.role_name]
        .filter(Boolean)
        .some((value) => value?.toLowerCase().includes(normalizedSearch)),
    );
  }, [search, staff]);

  const staffPagination = useTablePagination(filteredStaff);
  const paginatedStaff = staffPagination.pageItems;

  function openCreateForm() {
    setFormErrors({});
    setFormState({
      mode: "create",
      staff: null,
      values: emptyStaffForm(roles[0]?.id ?? ""),
    });
  }

  function openEditForm(member: SettingsStaff) {
    setFormErrors({});
    setFormState({
      mode: "edit",
      staff: member,
      values: staffToForm(member),
    });
  }

  async function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();

    if (!formState) {
      return;
    }

    const nextErrors = validateStaffForm(formState.values);
    setFormErrors(nextErrors);

    if (Object.values(nextErrors).some(Boolean)) {
      return;
    }

    try {
      setSaving(true);
      if (formState.mode === "create") {
        await createStaff(formState.values);
        showToast("Staff invite email sent.", "success");
      } else if (formState.staff) {
        await updateStaff(
          formState.staff.id,
          formState.values,
          formState.staff.status,
        );
        showToast("Staff profile updated.", "success");
      }
      setFormState(null);
      await loadData();
    } catch (nextError) {
      showToast(
        nextError instanceof Error ? nextError.message : "Staff save failed.",
        "error",
      );
    } finally {
      setSaving(false);
    }
  }

  async function handleResendInvite(member: SettingsStaff) {
    try {
      setOpenStaffMenuId(null);
      setResendingStaffId(member.id);
      await resendStaffInvite(member.id);
      showToast("A fresh staff invite email was sent.", "success");
      await loadData();
    } catch (nextError) {
      showToast(
        nextError instanceof Error ? nextError.message : "Invite resend failed.",
        "error",
      );
    } finally {
      setResendingStaffId(null);
    }
  }

  async function handleDeleteInvitedStaff() {
    if (!deleteTarget) {
      return;
    }

    try {
      setDeleting(true);
      await deleteInvitedStaff(deleteTarget.id);
      showToast("Invited staff member deleted.", "success");
      setDeleteTarget(null);
      await loadData();
    } catch (nextError) {
      showToast(
        nextError instanceof Error ? nextError.message : "Staff delete failed.",
        "error",
      );
    } finally {
      setDeleting(false);
    }
  }

  async function setMemberStatus(member: SettingsStaff, status: StaffStatus) {
    try {
      setStatusSaving(true);
      if (reductionOnly && status === "inactive") {
        await deactivateStaffForSeatLimit(member.id);
      } else {
        await updateStaff(member.id, { ...staffToForm(member), status });
      }
      showToast(
        status === "active" ? "Staff activated." : "Staff deactivated.",
        "success",
      );
      setStatusTarget(null);
      await loadData();
    } catch (nextError) {
      showToast(
        nextError instanceof Error ? nextError.message : "Status update failed.",
        "error",
      );
    } finally {
      setStatusSaving(false);
    }
  }

  return (
    <div className="space-y-3">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <SectionTitle title="Staff Management" />
        {!reductionOnly ? <Button onClick={openCreateForm}>Add Staff</Button> : null}
      </div>

      <Toolbar>
        <SearchInput
          placeholder="Search staff, email, phone, or role"
          value={search}
          onChange={setSearch}
        />
      </Toolbar>

      {loading ? <LoadingSkeleton /> : null}
      {error ? <EmptyState title="Could not load staff" description={error} /> : null}
      {!loading && !error && filteredStaff.length === 0 ? (
        <EmptyState
          title="No staff found"
          description="Create staff profiles before team members sign in."
          action={!reductionOnly ? <Button onClick={openCreateForm}>Add Staff</Button> : undefined}
        />
      ) : null}

      {!loading && !error && filteredStaff.length > 0 ? (
        <>
          <div className="hidden overflow-hidden rounded-xl border border-stone-200 bg-white shadow-sm xl:block">
            <table className="w-full border-collapse text-left text-sm">
              <thead className="bg-stone-50 text-xs font-semibold uppercase tracking-wide text-slate-500">
                <tr>
                  <th className="px-3 py-2.5">Name</th>
                  <th className="px-3 py-2.5">Phone</th>
                  <th className="px-3 py-2.5">Email</th>
                  <th className="px-3 py-2.5">Role</th>
                  <th className="px-3 py-2.5">Status</th>
                  <th className="px-3 py-2.5 text-right">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-stone-100">
                {paginatedStaff.map((member) => (
                  <tr key={member.id}>
                    <td className="px-3 py-2.5 font-semibold text-slate-950">
                      {member.full_name ?? "-"}
                    </td>
                    <td className="px-3 py-2.5">{member.phone ?? "-"}</td>
                    <td className="px-3 py-2.5">{member.email ?? "-"}</td>
                    <td className="px-3 py-2.5">{member.role_name ?? "No role"}</td>
                    <td className="px-3 py-2.5">
                      <StaffStatusBadge value={member.status} />
                    </td>
                    <td className="px-3 py-2.5">
                      <StaffRowActions
                        isMenuOpen={openStaffMenuId === member.id}
                        lastLogin={formatDateTime(member.last_login_at)}
                        member={member}
                        reductionOnly={reductionOnly}
                        resending={resendingStaffId === member.id}
                        onEdit={() => openEditForm(member)}
                        onDelete={() => {
                          setOpenStaffMenuId(null);
                          setDeleteTarget(member);
                        }}
                        onMenuOpenChange={(isOpen) =>
                          setOpenStaffMenuId(isOpen ? member.id : null)
                        }
                        onResend={() => void handleResendInvite(member)}
                        onStatusAction={() => {
                          setOpenStaffMenuId(null);
                          setStatusTarget(member);
                        }}
                      />
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          <div className="grid gap-3 xl:hidden">
            {paginatedStaff.map((member) => (
              <article
                key={member.id}
                className="rounded-xl border border-stone-200 bg-white p-3 shadow-sm"
              >
                <div className="flex items-start justify-between gap-3">
                  <div className="min-w-0">
                    <h2 className="truncate text-base font-semibold text-slate-950">
                      {member.full_name ?? "Staff user"}
                    </h2>
                    <p className="mt-1 text-sm text-slate-600">
                      {member.email ?? member.phone ?? "-"}
                    </p>
                  </div>
                  <StaffStatusBadge value={member.status} />
                </div>
                <dl className="mt-3 grid grid-cols-2 gap-3 text-sm">
                  <Detail label="Role" value={member.role_name ?? "No role"} />
                  <Detail label="Phone" value={member.phone ?? "-"} />
                  <Detail label="Email" value={member.email ?? "-"} />
                </dl>
                <div className="mt-3 flex justify-end">
                  <StaffRowActions
                    isMenuOpen={openStaffMenuId === member.id}
                    lastLogin={formatDateTime(member.last_login_at)}
                    member={member}
                    reductionOnly={reductionOnly}
                    resending={resendingStaffId === member.id}
                    onEdit={() => openEditForm(member)}
                    onDelete={() => {
                      setOpenStaffMenuId(null);
                      setDeleteTarget(member);
                    }}
                    onMenuOpenChange={(isOpen) =>
                      setOpenStaffMenuId(isOpen ? member.id : null)
                    }
                    onResend={() => void handleResendInvite(member)}
                    onStatusAction={() => {
                      setOpenStaffMenuId(null);
                      setStatusTarget(member);
                    }}
                  />
                </div>
              </article>
            ))}
          </div>
          <TablePagination label="staff" pagination={staffPagination} />
        </>
      ) : null}

      {formState ? (
        <StaffFormModal
          title={formState.mode === "create" ? "Add Staff" : "Edit Staff"}
          values={formState.values}
          setValues={(values) =>
            setFormState((current) => (current ? { ...current, values } : current))
          }
          roles={roles}
          errors={formErrors}
          onClose={() => setFormState(null)}
          onSubmit={handleSubmit}
          saving={saving}
          memberStatus={formState.staff?.status ?? null}
          submitLabel={formState.mode === "create" ? "Send Invite" : "Save Staff"}
        />
      ) : null}

      {statusTarget ? (
        <ConfirmDialog
          title="Deactivate staff?"
          description={`This will block ${statusTarget.full_name ?? "this staff member"} from accessing the workspace.`}
          confirmLabel="Deactivate"
          confirmingLabel="Deactivating..."
          confirming={statusSaving}
          onCancel={() => setStatusTarget(null)}
          onConfirm={() => void setMemberStatus(statusTarget, "inactive")}
        />
      ) : null}

      {deleteTarget ? (
        <ConfirmDialog
          title="Delete invited staff?"
          description={`This permanently removes the pending invitation for ${deleteTarget.full_name ?? deleteTarget.email ?? "this staff member"}.`}
          confirmLabel="Delete invitation"
          confirmingLabel="Deleting..."
          confirming={deleting}
          onCancel={() => setDeleteTarget(null)}
          onConfirm={() => void handleDeleteInvitedStaff()}
        />
      ) : null}
    </div>
  );
}

export function RolesPage() {
  const [roles, setRoles] = useState<SettingsRole[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  async function loadData() {
    try {
      setLoading(true);
      setError(null);
      const nextRoles = await fetchSettingsRoles();
      setRoles(nextRoles);
    } catch (nextError) {
      setError(
        nextError instanceof Error ? nextError.message : "Unable to load roles.",
      );
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    void loadData();
  }, []);

  return (
    <div className="space-y-5">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <SectionTitle title="Standard Roles" />
        <Badge tone="blue">Locked presets</Badge>
      </div>
      <p className="max-w-3xl text-sm leading-6 text-slate-600">
        EPC workspaces use locked standard roles. Admins can assign these roles
        to staff, while permission definitions are managed by the platform so
        pricing, delete access, and tenant controls stay consistent.
      </p>

      {loading ? <LoadingSkeleton /> : null}
      {error ? <EmptyState title="Could not load roles" description={error} /> : null}
      {!loading && !error && roles.length === 0 ? (
        <EmptyState
          title="No standard roles found"
          description="The standard roles will be seeded automatically by the platform."
        />
      ) : null}

      {!loading && !error && roles.length > 0 ? (
        <div className="grid gap-3">
          {roles.map((role) => (
            <article
              key={role.id}
              className="rounded-xl border border-stone-200 bg-white p-4 shadow-sm"
            >
              <div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between">
                <div className="min-w-0">
                  <div className="flex flex-wrap items-center gap-2">
                    <h2 className="text-base font-semibold text-slate-950">
                      {role.role_name}
                    </h2>
                    {role.is_system_role ? <Badge tone="blue">System</Badge> : null}
                  </div>
                  <p className="mt-1 text-sm leading-6 text-slate-600">
                    {role.description ?? "No description"}
                  </p>
                </div>
                <div className="flex flex-wrap items-center gap-2">
                  <Badge>{role.permission_count} permissions</Badge>
                  <Badge tone="green">Assignable</Badge>
                </div>
              </div>
            </article>
          ))}
        </div>
      ) : null}
    </div>
  );
}

function StaffFormModal({
  title,
  values,
  setValues,
  roles,
  errors,
  onClose,
  onSubmit,
  saving,
  memberStatus,
  submitLabel,
}: {
  title: string;
  values: StaffFormValues;
  setValues: (values: StaffFormValues) => void;
  roles: SettingsRole[];
  errors: Record<string, string>;
  onClose: () => void;
  onSubmit: (event: FormEvent<HTMLFormElement>) => void;
  saving: boolean;
  memberStatus: string | null;
  submitLabel: string;
}) {
  const update = (key: keyof StaffFormValues, value: string) =>
    setValues({ ...values, [key]: value });

  return (
    <Modal
      title={title}
      onClose={onClose}
      onSubmit={onSubmit}
      submitLabel={submitLabel}
      submitting={saving}
    >
      <TextInput
        label="Full Name"
        value={values.full_name}
        onChange={(value) => update("full_name", value)}
        error={errors.full_name}
        required
      />
      <TextInput
        label="Phone"
        value={values.phone}
        onChange={(value) => update("phone", value)}
        error={errors.phone}
      />
      <TextInput
        label="Email"
        type="email"
        value={values.email}
        onChange={(value) => update("email", value)}
        error={errors.email}
        disabled={memberStatus !== null && memberStatus !== "invited"}
        required
      />
      <SelectInput
        label="Role"
        value={values.role_id}
        onChange={(value) => update("role_id", value)}
        options={[
          { value: "", label: "No role" },
          ...roles.map((role) => ({
            value: role.id,
            label: role.role_name,
          })),
        ]}
      />
      {memberStatus === "active" ? (
        <SelectInput
          label="Status"
          value={values.status}
          onChange={(value) => update("status", value)}
          options={staffStatusOptions
            .filter((status) => status !== "invited")
            .map((status) => ({
              value: status,
              label: labelize(status),
            }))}
        />
      ) : null}
    </Modal>
  );
}

function StaffStatusBadge({ value }: { value: string | null | undefined }) {
  const tone =
    value === "active" ? "green" : value === "inactive" ? "red" : "amber";

  return <Badge tone={tone}>{labelize(value)}</Badge>;
}

function StaffRowActions({
  isMenuOpen,
  lastLogin,
  member,
  reductionOnly,
  resending,
  onDelete,
  onEdit,
  onMenuOpenChange,
  onResend,
  onStatusAction,
}: {
  isMenuOpen: boolean;
  lastLogin: string;
  member: SettingsStaff;
  reductionOnly: boolean;
  resending: boolean;
  onDelete: () => void;
  onEdit: () => void;
  onMenuOpenChange: (isOpen: boolean) => void;
  onResend: () => void;
  onStatusAction: () => void;
}) {
  const showDeactivate = reductionOnly
    ? member.status !== "inactive"
    : member.status === "active";

  return (
    <div
      className="relative ml-auto flex w-fit items-center justify-end gap-1.5"
      onBlur={(event) => {
        if (!event.currentTarget.contains(event.relatedTarget)) {
          onMenuOpenChange(false);
        }
      }}
    >
      {!reductionOnly ? (
        <button
          aria-label={`Edit ${member.full_name ?? "staff member"}`}
          className="inline-flex h-9 w-9 items-center justify-center rounded-lg border border-stone-200 bg-white text-slate-700 shadow-sm transition hover:bg-orange-50 hover:text-[#06173f] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-orange-500"
          onClick={onEdit}
          type="button"
        >
          <PencilIcon />
        </button>
      ) : null}
      <button
        aria-expanded={isMenuOpen}
        aria-haspopup="menu"
        aria-label={`More actions for ${member.full_name ?? "staff member"}`}
        className="inline-flex h-9 w-9 items-center justify-center rounded-lg border border-stone-200 bg-white text-slate-700 shadow-sm transition hover:bg-orange-50 hover:text-[#06173f] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-orange-500"
        onClick={() => onMenuOpenChange(!isMenuOpen)}
        type="button"
      >
        <VerticalDotsIcon />
      </button>

      {isMenuOpen ? (
        <div
          aria-label="Staff actions"
          className="absolute right-0 top-[calc(100%+0.45rem)] z-30 w-56 rounded-lg border border-stone-200 bg-white p-1.5 text-left shadow-xl"
          role="menu"
        >
          <div className="rounded-md px-3 py-2">
            <p className="text-xs font-semibold uppercase tracking-wide text-slate-500">
              Last login
            </p>
            <p className="mt-1 text-sm font-medium text-slate-900">
              {lastLogin}
            </p>
          </div>
          {!reductionOnly && member.status === "invited" ? (
            <>
              <button
                className="mt-1 flex w-full items-center rounded-md px-3 py-2 text-left text-sm font-semibold text-[#06173f] transition hover:bg-orange-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-orange-500 disabled:cursor-not-allowed disabled:opacity-60"
                disabled={resending}
                onClick={onResend}
                role="menuitem"
                type="button"
              >
                {resending ? "Resending..." : "Resend invite"}
              </button>
              <button
                className="flex w-full items-center rounded-md px-3 py-2 text-left text-sm font-semibold text-rose-700 transition hover:bg-rose-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-rose-500"
                onClick={onDelete}
                role="menuitem"
                type="button"
              >
                Delete invitation
              </button>
            </>
          ) : null}
          {showDeactivate ? (
            <button
              className="mt-1 flex w-full items-center rounded-md px-3 py-2 text-left text-sm font-semibold text-rose-700 transition hover:bg-orange-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-orange-500"
              onClick={onStatusAction}
              role="menuitem"
              type="button"
            >
              {reductionOnly ? "Deactivate for Core" : "Deactivate"}
            </button>
          ) : null}
        </div>
      ) : null}
    </div>
  );
}

function PencilIcon() {
  return (
    <svg aria-hidden="true" className="h-4 w-4" fill="none" viewBox="0 0 24 24">
      <path
        d="M4.5 19.5h4l10-10a2.1 2.1 0 0 0-3-3l-10 10-1 3Z"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="1.9"
      />
      <path
        d="m14 8 2 2"
        stroke="currentColor"
        strokeLinecap="round"
        strokeWidth="1.9"
      />
    </svg>
  );
}

function VerticalDotsIcon() {
  return (
    <svg aria-hidden="true" className="h-5 w-5" fill="currentColor" viewBox="0 0 24 24">
      <circle cx="12" cy="5.5" r="1.6" />
      <circle cx="12" cy="12" r="1.6" />
      <circle cx="12" cy="18.5" r="1.6" />
    </svg>
  );
}

function SettingsCard({
  title,
  description,
}: {
  title: string;
  description: string;
}) {
  return (
    <section className="rounded-xl border border-stone-200 bg-white p-5 shadow-sm">
      <h2 className="text-base font-semibold text-slate-950">{title}</h2>
      <p className="mt-2 text-sm leading-6 text-slate-600">{description}</p>
    </section>
  );
}

function SectionTitle({
  title,
  description,
}: {
  title: string;
  description?: string;
}) {
  return (
    <div>
      <h2 className="text-base font-semibold tracking-normal text-slate-950">
        {title}
      </h2>
      {description ? (
        <p className="mt-1 text-sm leading-5 text-slate-600">{description}</p>
      ) : null}
    </div>
  );
}

function SettingsSection({
  title,
  children,
}: {
  title: string;
  children: ReactNode;
}) {
  return (
    <section className="grid gap-3 border-b border-stone-100 pb-4 last:border-b-0 last:pb-0 lg:grid-cols-[11rem_minmax(0,1fr)]">
      <h3 className="text-sm font-semibold text-slate-900">{title}</h3>
      <div className="min-w-0">{children}</div>
    </section>
  );
}

function ProfileSettingsCard({
  title,
  description,
  children,
}: {
  title: string;
  description: string;
  children: ReactNode;
}) {
  return (
    <section className="overflow-hidden rounded-xl border border-stone-200 bg-white shadow-sm">
      <div className="border-b border-stone-100 px-4 py-3.5">
        <h3 className="text-sm font-semibold text-slate-950">{title}</h3>
        <p className="mt-0.5 text-xs leading-5 text-slate-500">{description}</p>
      </div>
      <div className="grid gap-4 p-4">{children}</div>
    </section>
  );
}

function Detail({ label, value }: { label: string; value: ReactNode }) {
  return (
    <div>
      <dt className="text-xs font-semibold uppercase tracking-wide text-slate-500">
        {label}
      </dt>
      <dd className="mt-1 font-medium text-slate-900">{value}</dd>
    </div>
  );
}
