import type { MobileResource } from "@bizlee/contracts";

export type FieldKind = "text" | "phone" | "email" | "number" | "multiline" | "date";
export type FormField = { key: string; label: string; kind?: FieldKind; required?: boolean };
export type ModuleConfig = { resource: MobileResource; title: string; singular: string; description: string; createEnabled: boolean; fields: FormField[]; detailLabels: Record<string, string> };

export const moduleConfigs: Record<MobileResource, ModuleConfig> = {
  enquiries: { resource: "enquiries", title: "Enquiries", singular: "enquiry", description: "Capture a new sales opportunity.", createEnabled: true, fields: [{ key: "fullName", label: "Full name", required: true }, { key: "phone", label: "Phone", kind: "phone", required: true }, { key: "email", label: "Email", kind: "email" }, { key: "city", label: "City" }, { key: "address", label: "Site address", kind: "multiline" }, { key: "leadSource", label: "Lead source" }, { key: "requirementType", label: "Requirement type" }, { key: "notes", label: "Notes", kind: "multiline" }], detailLabels: { lead_code: "Enquiry ID", full_name: "Contact", phone: "Phone", city: "City", lead_source: "Lead source", status: "Status", updated_at: "Last updated" } },
  customers: { resource: "customers", title: "Customers", singular: "customer", description: "Add a customer profile and contact details.", createEnabled: true, fields: [{ key: "fullName", label: "Full name", required: true }, { key: "phone", label: "Phone", kind: "phone", required: true }, { key: "email", label: "Email", kind: "email" }, { key: "city", label: "City" }, { key: "address", label: "Address", kind: "multiline" }, { key: "customerType", label: "Customer type" }, { key: "leadSource", label: "Lead source" }, { key: "notes", label: "Notes", kind: "multiline" }], detailLabels: { customer_code: "Customer ID", full_name: "Contact", business_name: "Business", phone: "Phone", city: "City", customer_segment: "Segment", status: "Status", updated_at: "Last updated" } },
  "site-surveys": { resource: "site-surveys", title: "Site surveys", singular: "site survey", description: "Prepare a survey visit for the field team.", createEnabled: false, fields: [{ key: "siteAddress", label: "Site address", kind: "multiline", required: true }, { key: "city", label: "City", required: true }, { key: "scheduledAt", label: "Scheduled date", kind: "date" }, { key: "contactName", label: "Site contact" }, { key: "contactPhone", label: "Contact phone", kind: "phone" }, { key: "notes", label: "Survey notes", kind: "multiline" }], detailLabels: { survey_code: "Survey ID", site_address: "Site address", city: "City", status: "Status", scheduled_at: "Scheduled for", updated_at: "Last updated" } },
  quotations: { resource: "quotations", title: "Quotations", singular: "quotation", description: "Start a proposal with the essential system details.", createEnabled: false, fields: [{ key: "customer", label: "Customer or enquiry", required: true }, { key: "systemCapacity", label: "System capacity (kW)", kind: "number", required: true }, { key: "propertyType", label: "Property type" }, { key: "validUntil", label: "Valid until", kind: "date" }, { key: "notes", label: "Internal notes", kind: "multiline" }], detailLabels: { quotation_code: "Quotation ID", system_capacity_kw: "System capacity (kW)", total_amount: "Total amount", net_payable_amount: "Net payable", status: "Status", updated_at: "Last updated" } },
  projects: { resource: "projects", title: "Projects", singular: "project", description: "Set up the project overview and ownership.", createEnabled: false, fields: [{ key: "projectName", label: "Project name", required: true }, { key: "customer", label: "Customer", required: true }, { key: "systemCapacity", label: "System capacity (kW)", kind: "number" }, { key: "priority", label: "Priority" }, { key: "targetDate", label: "Target completion", kind: "date" }, { key: "notes", label: "Project notes", kind: "multiline" }], detailLabels: { project_code: "Project ID", project_name: "Project name", system_capacity_kw: "System capacity (kW)", project_status: "Status", priority: "Priority", updated_at: "Last updated" } },
  documents: { resource: "documents", title: "Documents", singular: "document", description: "Add document information before selecting a file.", createEnabled: false, fields: [{ key: "documentName", label: "Document name", required: true }, { key: "documentType", label: "Document type", required: true }, { key: "relatedTo", label: "Related record" }, { key: "description", label: "Description", kind: "multiline" }], detailLabels: { document_name: "Document name", document_type: "Type", mime_type: "File format", file_size: "File size", status: "Status", updated_at: "Last updated" } },
};
export function isMobileResource(value: string | undefined): value is MobileResource { return Boolean(value && value in moduleConfigs); }
