import { useState } from "react";
import { Alert, KeyboardAvoidingView, Platform, Pressable, SafeAreaView, StyleSheet, Text, TextInput } from "react-native";
import { useRouter } from "expo-router";
import { mobileApi } from "@/lib/api";
export default function EnrollmentScreen() {
  const [organizationName, setOrganizationName] = useState(""); const [fullName, setFullName] = useState(""); const [phone, setPhone] = useState(""); const [busy, setBusy] = useState(false); const router = useRouter();
  async function createWorkspace() { setBusy(true); try { await mobileApi.enroll({ organizationName, fullName, phone: phone || undefined }); router.replace("/(tabs)/today"); } catch (error) { Alert.alert("Workspace not created", error instanceof Error ? error.message : "Try again"); } finally { setBusy(false); } }
  return <SafeAreaView style={styles.safe}><KeyboardAvoidingView behavior={Platform.OS === "ios" ? "padding" : undefined} style={styles.body}><Text style={styles.eyebrow}>NEW WORKSPACE</Text><Text style={styles.title}>Set up your EPC company</Text><Text style={styles.copy}>This creates an isolated Bizlee workspace and assigns you its Admin role.</Text><TextInput accessibilityLabel="Company name" onChangeText={setOrganizationName} placeholder="Company name" style={styles.input} value={organizationName} /><TextInput accessibilityLabel="Full name" onChangeText={setFullName} placeholder="Your full name" style={styles.input} value={fullName} /><TextInput accessibilityLabel="Phone" keyboardType="phone-pad" onChangeText={setPhone} placeholder="Phone (optional)" style={styles.input} value={phone} /><Pressable disabled={busy || organizationName.trim().length < 2 || fullName.trim().length < 2} onPress={createWorkspace} style={styles.button}><Text style={styles.buttonText}>{busy ? "Creating…" : "Create workspace"}</Text></Pressable></KeyboardAvoidingView></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: "#f8fafc" }, body: { flex: 1, justifyContent: "center", padding: 24, gap: 14 }, eyebrow: { color: "#f97316", fontWeight: "900", letterSpacing: 2 }, title: { color: "#06173f", fontSize: 30, fontWeight: "800" }, copy: { color: "#64748b", lineHeight: 22, marginBottom: 8 }, input: { backgroundColor: "white", borderWidth: 1, borderColor: "#cbd5e1", borderRadius: 12, padding: 16 }, button: { backgroundColor: "#0f766e", borderRadius: 12, padding: 16, alignItems: "center" }, buttonText: { color: "white", fontWeight: "800" } });
