import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useQuery } from "@tanstack/react-query";
import { mobileApi } from "@/lib/api";
import type { ModuleConfig } from "@/modules/moduleConfig";
import { colors } from "@/theme";
function display(value: unknown) { if (value === null || value === undefined || value === "") return "—"; if (typeof value === "string" && /^\d{4}-\d{2}-\d{2}T/.test(value)) return new Date(value).toLocaleString(); return String(value).replaceAll("_", " "); }
export function RecordDetail({ config, id }: { config: ModuleConfig; id: string }) {
  const query = useQuery({ queryKey: [config.resource, id], queryFn: () => mobileApi.detail(config.resource, id) });
  if (query.isLoading) return <View style={styles.center}><ActivityIndicator color={colors.orange} size="large" /><Text style={styles.loading}>Loading {config.singular}…</Text></View>;
  if (query.error) return <View style={styles.center}><Text style={styles.errorTitle}>Unable to open this record</Text><Text style={styles.errorCopy}>{query.error instanceof Error ? query.error.message : "Please try again."}</Text><Pressable onPress={() => void query.refetch()} style={styles.retry}><Text style={styles.retryText}>Try again</Text></Pressable></View>;
  const record = query.data?.data ?? {}; const headingKey = config.resource === "projects" ? "project_name" : config.resource === "documents" ? "document_name" : "full_name"; const heading = display(record[headingKey] ?? record.quotation_code ?? record.survey_code);
  return <ScrollView style={styles.page} contentContainerStyle={styles.content}><View style={styles.hero}><Text style={styles.eyebrow}>{config.singular.toUpperCase()}</Text><Text style={styles.title}>{heading}</Text>{record.status || record.project_status ? <View style={styles.badge}><Text style={styles.badgeText}>{display(record.status ?? record.project_status)}</Text></View> : null}</View><View style={styles.card}><Text style={styles.sectionTitle}>Overview</Text>{Object.entries(config.detailLabels).map(([key, label]) => <View key={key} style={styles.row}><Text style={styles.label}>{label}</Text><Text selectable style={styles.value}>{display(record[key])}</Text></View>)}</View><View style={styles.card}><Text style={styles.sectionTitle}>Activity</Text><Text style={styles.empty}>Updates and linked activity will appear here as the workflow progresses.</Text></View></ScrollView>;
}
const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: colors.background }, content: { padding: 18, paddingBottom: 42, gap: 14 }, center: { flex: 1, backgroundColor: colors.background, alignItems: "center", justifyContent: "center", padding: 28 }, loading: { color: colors.muted, marginTop: 12 }, errorTitle: { color: colors.navy, fontSize: 20, fontWeight: "900", textAlign: "center" }, errorCopy: { color: colors.muted, textAlign: "center", marginTop: 8 }, retry: { backgroundColor: colors.navy, paddingHorizontal: 20, paddingVertical: 12, borderRadius: 12, marginTop: 18 }, retryText: { color: "white", fontWeight: "800" }, hero: { backgroundColor: colors.navy, borderRadius: 20, padding: 20 }, eyebrow: { color: colors.orange, fontSize: 11, fontWeight: "900", letterSpacing: 1.5 }, title: { color: "white", fontSize: 24, fontWeight: "900", marginTop: 7 }, badge: { alignSelf: "flex-start", backgroundColor: "#ffffff18", borderColor: "#ffffff30", borderWidth: 1, borderRadius: 999, paddingHorizontal: 10, paddingVertical: 5, marginTop: 13 }, badgeText: { color: "white", fontSize: 12, fontWeight: "800", textTransform: "capitalize" }, card: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: 18, padding: 17 }, sectionTitle: { color: colors.navy, fontSize: 17, fontWeight: "900", marginBottom: 10 }, row: { flexDirection: "row", justifyContent: "space-between", gap: 16, paddingVertical: 11, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border }, label: { color: colors.muted, fontSize: 13, flex: 1 }, value: { color: colors.ink, fontSize: 13, fontWeight: "700", textAlign: "right", flex: 1.25, textTransform: "capitalize" }, empty: { color: colors.muted, lineHeight: 20 } });
