import { useState } from "react";
import { ActivityIndicator, FlatList, Pressable, RefreshControl, StyleSheet, Text, TextInput, View } from "react-native";
import { useQuery } from "@tanstack/react-query";
import { useRouter } from "expo-router";
import type { MobileResource } from "@bizlee/contracts";
import { mobileApi } from "@/lib/api";
export function ResourceList({ resource, title, showCreate = false }: { resource: MobileResource; title: string; showCreate?: boolean }) {
  const [search, setSearch] = useState(""); const router = useRouter(); const query = useQuery({ queryKey: [resource, search], queryFn: () => mobileApi.list(resource, search) });
  return <View style={styles.page}><View style={styles.heading}><Text style={styles.title}>{title}</Text>{showCreate ? <Pressable accessibilityLabel={`Add ${title}`} onPress={() => router.push(`/form/${resource}` as never)} style={styles.add}><Text style={styles.addText}>+</Text></Pressable> : null}</View><TextInput accessibilityLabel={`Search ${title}`} onChangeText={setSearch} placeholder={`Search ${title.toLowerCase()}`} style={styles.search} value={search} />{query.isLoading ? <ActivityIndicator style={styles.loading} /> : <FlatList data={query.data?.data ?? []} keyExtractor={(item) => item.id} refreshControl={<RefreshControl refreshing={query.isFetching} onRefresh={() => void query.refetch()} />} renderItem={({ item }) => <Pressable onPress={() => router.push(`/record/${resource}/${item.id}` as never)} style={({ pressed }) => [styles.card, pressed && styles.pressed]}><View style={styles.row}><Text style={styles.cardTitle}>{item.title}</Text>{item.status && <Text style={styles.badge}>{item.status}</Text>}</View><View style={styles.row}><Text style={styles.meta}>{[item.code, item.subtitle].filter(Boolean).join(" · ")}</Text><Text style={styles.chevron}>›</Text></View></Pressable>} ListEmptyComponent={<Text style={styles.empty}>{query.error instanceof Error ? query.error.message : "No records found"}</Text>} />}</View>;
}
const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: "#f8fafc", paddingTop: 14 }, heading: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: 18, marginBottom: 12 }, title: { fontSize: 28, fontWeight: "800", color: "#06173f" }, add: { width: 42, height: 42, borderRadius: 13, backgroundColor: "#f97316", alignItems: "center", justifyContent: "center" }, addText: { color: "white", fontSize: 27, lineHeight: 29, fontWeight: "700" }, search: { marginHorizontal: 18, marginBottom: 10, backgroundColor: "white", borderWidth: 1, borderColor: "#e2e8f0", borderRadius: 12, padding: 13 }, loading: { marginTop: 40 }, card: { backgroundColor: "white", marginHorizontal: 18, marginVertical: 5, borderRadius: 14, padding: 15, borderWidth: 1, borderColor: "#e2e8f0" }, pressed: { opacity: 0.7 }, row: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", gap: 8 }, cardTitle: { flex: 1, fontSize: 16, fontWeight: "700", color: "#0f172a" }, badge: { color: "#0f766e", textTransform: "capitalize", fontSize: 12, fontWeight: "700" }, meta: { flex: 1, color: "#64748b", marginTop: 6 }, chevron: { color: "#94a3b8", fontSize: 22 }, empty: { textAlign: "center", color: "#64748b", marginTop: 40 } });
