import { useState } from "react";
import { ActivityIndicator, FlatList, RefreshControl, StyleSheet, Text, TextInput, View } from "react-native";
import { useQuery } from "@tanstack/react-query";
import type { MobileResource } from "@bizlee/contracts";
import { mobileApi } from "@/lib/api";
export function ResourceList({ resource, title }: { resource: MobileResource; title: string }) {
  const [search, setSearch] = useState(""); const query = useQuery({ queryKey: [resource, search], queryFn: () => mobileApi.list(resource, search) });
  return <View style={styles.page}><Text style={styles.title}>{title}</Text><TextInput accessibilityLabel={`Search ${title}`} onChangeText={setSearch} placeholder={`Search ${title.toLowerCase()}`} style={styles.search} value={search} />{query.isLoading ? <ActivityIndicator style={styles.loading} /> : <FlatList data={query.data?.data ?? []} keyExtractor={(item) => item.id} refreshControl={<RefreshControl refreshing={query.isFetching} onRefresh={() => void query.refetch()} />} renderItem={({ item }) => <View style={styles.card}><View style={styles.row}><Text style={styles.cardTitle}>{item.title}</Text>{item.status && <Text style={styles.badge}>{item.status}</Text>}</View><Text style={styles.meta}>{[item.code, item.subtitle].filter(Boolean).join(" · ")}</Text></View>} ListEmptyComponent={<Text style={styles.empty}>{query.error instanceof Error ? query.error.message : "No records found"}</Text>} />}</View>;
}
const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: "#f8fafc", paddingTop: 14 }, title: { fontSize: 28, fontWeight: "800", color: "#06173f", paddingHorizontal: 18, marginBottom: 12 }, search: { marginHorizontal: 18, marginBottom: 10, backgroundColor: "white", borderWidth: 1, borderColor: "#e2e8f0", borderRadius: 12, padding: 13 }, loading: { marginTop: 40 }, card: { backgroundColor: "white", marginHorizontal: 18, marginVertical: 5, borderRadius: 14, padding: 15, borderWidth: 1, borderColor: "#e2e8f0" }, row: { flexDirection: "row", justifyContent: "space-between", gap: 8 }, cardTitle: { flex: 1, fontSize: 16, fontWeight: "700", color: "#0f172a" }, badge: { color: "#0f766e", textTransform: "capitalize", fontSize: 12, fontWeight: "700" }, meta: { color: "#64748b", marginTop: 6 }, empty: { textAlign: "center", color: "#64748b", marginTop: 40 } });
